// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject


package main

import (
	"w4work"
	"w4work/internal/biz"
	"w4work/internal/conf"
	"w4work/internal/data"
	"w4work/internal/server"
	"w4work/internal/service"
)

// Injectors from wire.go:

// initApp init w4work application.
func initApp(confServer *conf.HttpConf, confData *conf.RedisConf) (*w4work.App, error) {
	dataData, err := data.NewData(confData)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase)
	httpServer := server.NewHTTPServer(confServer,userService)
	app := newApp(httpServer)
	return app, nil
}
